// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLG5gOdlX-VWV3lNzoLSRDpSsYb-aQRrg',
    appId: '1:28621946941:web:9275ac4ddecc6c057dea54',
    messagingSenderId: '28621946941',
    projectId: 'flutterelegantmedia',
    authDomain: 'flutterelegantmedia.firebaseapp.com',
    storageBucket: 'flutterelegantmedia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Xyx3IriLVW2ojFo8dJa2ex_B0EI4syk',
    appId: '1:28621946941:android:61b0021c059d5e3d7dea54',
    messagingSenderId: '28621946941',
    projectId: 'flutterelegantmedia',
    storageBucket: 'flutterelegantmedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbre0CxCyzMKn5kbAW1V56x20MZZ-pyJw',
    appId: '1:28621946941:ios:72218d343d5bf1847dea54',
    messagingSenderId: '28621946941',
    projectId: 'flutterelegantmedia',
    storageBucket: 'flutterelegantmedia.appspot.com',
    iosBundleId: 'com.flutter.flutterelegantmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbre0CxCyzMKn5kbAW1V56x20MZZ-pyJw',
    appId: '1:28621946941:ios:72218d343d5bf1847dea54',
    messagingSenderId: '28621946941',
    projectId: 'flutterelegantmedia',
    storageBucket: 'flutterelegantmedia.appspot.com',
    iosBundleId: 'com.flutter.flutterelegantmedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLG5gOdlX-VWV3lNzoLSRDpSsYb-aQRrg',
    appId: '1:28621946941:web:2a42890055ed383e7dea54',
    messagingSenderId: '28621946941',
    projectId: 'flutterelegantmedia',
    authDomain: 'flutterelegantmedia.firebaseapp.com',
    storageBucket: 'flutterelegantmedia.appspot.com',
  );
}
